<a href="https://colab.research.google.com/github/DavidB363/file-store/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Question 1.


import numpy as np

# Simple array creation.
a = np.array([[0, 1],[2, 3],[4, 5],[6, 7]])

# Print out the values of the array.
print(a)

print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension -', a.ndim)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Shape = (4, 2)
Size = 8
Dimension - 2


In [28]:
# Question 2.

a = np.array([[5, 1, 9, 3, 0, 4, 2, 7, 8, 6]])

# Print out the values of the array.
print(a)

print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension -', a.ndim)

#sort in ascending order
a_sorted_asc = np.sort(a)
a_sorted_asc








[[5 1 9 3 0 4 2 7 8 6]]
Shape = (1, 10)
Size = 10
Dimension - 2


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
#sort in descending order
a_sorted_des = -np.sort(-a)
a_sorted_des

array([[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [49]:
# Question 3.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
X = np.reshape(x, (-1, 3))
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# Question 4.

A = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
A


array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [45]:
B= np.array([[10, 20, 30,40],
       [40, 50, 60,70]])
B

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [48]:
np.vstack((A,B))

ValueError: ignored