<a href="https://colab.research.google.com/github/DavidB363/file-store/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Question 1.
# Create 2x2 array and print its attributes.


import numpy as np

# Simple array creation.
a = np.array([[0, 1],[2, 3],[4, 5],[6, 7]])

# Print out the values of the array.
print(a)

print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension -', a.ndim)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Shape = (4, 2)
Size = 8
Dimension - 2


In [0]:
# Question 2.
# Create an array of dimension (1,10) and sort it in ascending and descending order.

a = np.array([[5, 1, 9, 3, 0, 4, 2, 7, 8, 6]])

# Print out the values of the array.
print(a)

print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension -', a.ndim)

#sort in ascending order
a_sorted_asc = np.sort(a)
a_sorted_asc








[[5 1 9 3 0 4 2 7 8 6]]
Shape = (1, 10)
Size = 10
Dimension - 2


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [0]:
#sort in descending order
a_sorted_des = -np.sort(-a)
a_sorted_des

array([[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [0]:
# Question 3.
# Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]].

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
X = np.reshape(x, (-1, 3))
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# Question 4.
# Stack two arrays of any size horizontally and vertically.

# Vertical stacking of arrays.
A = np.array([[1, 2, 3, 6],
       [4, 5, 6, 9],
       [7, 8, 9, 4]])
A


array([[1, 2, 3, 6],
       [4, 5, 6, 9],
       [7, 8, 9, 4]])

In [0]:
B= np.array([[10, 20, 30,40],
       [40, 50, 60,70]])
B

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [0]:

np.vstack((A,B))

array([[ 1,  2,  3,  6],
       [ 4,  5,  6,  9],
       [ 7,  8,  9,  4],
       [10, 20, 30, 40],
       [40, 50, 60, 70]])

In [0]:
# Horizontal stacking of arrays.
C=np.array([[5, 7, 8, 9, 3],
    [8, 9, 2, 7, 2],
    [4, 5, 7, 7, 1]])
C

array([[5, 7, 8, 9, 3],
       [8, 9, 2, 7, 2],
       [4, 5, 7, 7, 1]])

In [0]:
D=np.array([[8, 6],
    [3, 5],
    [9, 2]])
D

array([[8, 6],
       [3, 5],
       [9, 2]])

In [0]:
np.hstack((C,D))

array([[5, 7, 8, 9, 3, 8, 6],
       [8, 9, 2, 7, 2, 3, 5],
       [4, 5, 7, 7, 1, 9, 2]])

In [0]:
# Question 5.
#Create two array of same size and find commom elements.

# Finding the common elements in two arrays

C=np.array([[5, 7, 15, 9, 3],
    [14, 9, 2, 7, 2],
    [4, 5, 7, 7, 1]])

In [0]:
print('size =', C.size)
print('shape =',C.shape)


size = 15
shape = (3, 5)


In [0]:
D=np.array([[1, 3, 11],
    [2, 8, 2],
    [13, 9, 1],
    [15, 6, 7],
    [16, 8, 7],])

print('size =', D.size)
print('shape =',D.shape)

# Note that C and D have the same size, but different shape.

size = 15
shape = (5, 3)


In [0]:
np.intersect1d(C, D)

array([ 1,  2,  3,  7,  9, 15])

In [0]:
# Question 6.
# Finding the minumum and maximum values in each row and column of an array.

X = np.array([[12, 2, 3, 5, 8],
              [11, 15, 3, 3, 15],
              [6, 8, 11, 19, 1],
              [4, 11, 2, 7, 5],
              [4, 16, 6, 16, 17]])

X



array([[12,  2,  3,  5,  8],
       [11, 15,  3,  3, 15],
       [ 6,  8, 11, 19,  1],
       [ 4, 11,  2,  7,  5],
       [ 4, 16,  6, 16, 17]])

In [0]:
(num_rows,num_cols)=X.shape
num_rows

5

In [0]:
num_cols

5

In [0]:
for i in range(num_rows):
  print('Row:', i, 'Minimum is' , min(X[i,:]), 'Maximum is',  max(X[i,:]))

Row: 0 Minimum is 2 Maximum is 12
Row: 1 Minimum is 3 Maximum is 15
Row: 2 Minimum is 1 Maximum is 19
Row: 3 Minimum is 2 Maximum is 11
Row: 4 Minimum is 4 Maximum is 17


In [0]:
for j in range(num_rows):
  print('Column:', j, 'Minimum is' , min(X[:,j]), 'Maximum is',  max(X[:,j]))

Column: 0 Minimum is 4 Maximum is 12
Column: 1 Minimum is 2 Maximum is 16
Column: 2 Minimum is 2 Maximum is 11
Column: 3 Minimum is 3 Maximum is 19
Column: 4 Minimum is 1 Maximum is 17


In [0]:
# Question 7.
# Create an array of size 100 and compute the mean, median, standard deviation.

X=np.random.random((5, 20))
X



array([[0.34164509, 0.57363372, 0.90557644, 0.08869888, 0.5925604 ,
        0.22827699, 0.12187598, 0.38067789, 0.90434652, 0.60647254,
        0.47664524, 0.48391339, 0.60546204, 0.29538267, 0.58089546,
        0.03939159, 0.83385985, 0.50110292, 0.38303905, 0.38912378],
       [0.19851988, 0.10184272, 0.59942296, 0.05847788, 0.28593296,
        0.07896335, 0.2321355 , 0.47497826, 0.77009817, 0.03777493,
        0.1217578 , 0.52377947, 0.06827713, 0.06881563, 0.10684162,
        0.3497365 , 0.43400572, 0.38324321, 0.2436673 , 0.22435595],
       [0.74505038, 0.96054254, 0.35711092, 0.70412132, 0.01556355,
        0.21958408, 0.1736091 , 0.94266304, 0.64197463, 0.70445128,
        0.42735078, 0.80527798, 0.8885284 , 0.50469123, 0.27666026,
        0.8064643 , 0.69951627, 0.15167923, 0.07768628, 0.76879982],
       [0.1115209 , 0.820311  , 0.82889923, 0.29032384, 0.48803464,
        0.32360172, 0.86991549, 0.43079208, 0.11342845, 0.92170757,
        0.28087787, 0.43807104, 0.21640188, 0

In [0]:
X.size

100

In [0]:
# Mean.
np.mean(X)

0.45932678907376256

In [0]:
# Median.
np.median(X)

0.43239889957364475

In [0]:
# Standard Deviation.
np.std(X)

0.27837853859050654

In [0]:
# Question 8.
# Normalize a 5x5 random matrix.

X=np.random.random((5, 5))
X= 2020*X
X



array([[ 477.47706636,  523.37013386, 1379.17479395,  577.32700709,
         674.44941183],
       [ 947.26815513,  347.65852857, 2015.53231976, 1997.48357909,
        1560.28061772],
       [1814.71567094, 1547.52820539, 1109.63355656,  843.51611772,
        1108.53407285],
       [1338.64883648,  456.86391932, 1273.53593466,   28.36611213,
        1692.16490487],
       [  81.63239684, 1404.2795241 , 1908.68831691, 2002.06808433,
        1123.62151916]])

In [0]:
# This is ONE way to normalise the matrix.
# Subtract the mean.
X = X - X.mean()
# Divide by the maximum.
X = X / X.max()
# Numbers generated are between -1 and 1.
X

array([[-0.73560225, -0.6838147 ,  0.28190905, -0.62292764, -0.51333088],
       [-0.20547144, -0.88209461,  1.        ,  0.97963309,  0.48627601],
       [ 0.77339057,  0.47188569, -0.02225192, -0.32254934, -0.02349262],
       [ 0.23617796, -0.75886294,  0.16270199, -1.24239678,  0.63509945],
       [-1.182289  ,  0.31023822,  0.87943301,  0.98480643, -0.00646735]])

In [0]:
# Question 11.
#
# Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?
#
# The matrix equation y=Ax can be written using indices:-
# y(k)= Sum over j: A(k,j)*x(j)
#
# My thoughts:- A generalisation to higher dimensions could be;
#
# y(k) = Sum over i and j: A(i,j,k)*x(i,j)
#
# In the example i and j would range from 1 to 4. (0 to 3 in Python!),
# and k would range from 1 to 3 (0 to 2).
# So A would be a 3 by 4 by 4 matrix,  x a 4 by 4 matrix , and y a 3 by 1 matrix.
#


In [0]:
x = np.random.random((4, 4))
x

array([[0.95355241, 0.14531817, 0.91596153, 0.23498405],
       [0.98632485, 0.47690055, 0.60919026, 0.39637643],
       [0.35903103, 0.68500578, 0.50319243, 0.02301881],
       [0.36599612, 0.23057265, 0.57390192, 0.85000504]])

In [0]:
A = np.random.random((4, 4, 3))
A

array([[[0.33068356, 0.5530587 , 0.53392649],
        [0.24652459, 0.94105179, 0.2912648 ],
        [0.65618084, 0.20367151, 0.65430888],
        [0.67318769, 0.61125159, 0.57695789]],

       [[0.2815373 , 0.66016849, 0.1136774 ],
        [0.46200074, 0.64103192, 0.46470109],
        [0.88625247, 0.9681359 , 0.2615794 ],
        [0.39188137, 0.90658516, 0.39958232]],

       [[0.55364068, 0.83948415, 0.23318898],
        [0.68372854, 0.02327788, 0.20971887],
        [0.84878985, 0.7255959 , 0.73893669],
        [0.49290524, 0.48305231, 0.79528076]],

       [[0.28678742, 0.40745867, 0.05959372],
        [0.13184407, 0.08525674, 0.5257071 ],
        [0.10312467, 0.42639493, 0.22682911],
        [0.01729479, 0.77345399, 0.7429396 ]]])

In [0]:

y=np.array([0.0,0.0,0.0])

for k in range(3):
  s = 0.0
  for i in range(4):
    for j in range(4):
      s = s + A[i,j,k]*x[i,j]
  y[k]=s

y

array([3.61844768, 4.66480386, 3.4600456 ])