<a href="https://colab.research.google.com/github/DavidB363/file-store/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [183]:
# Question 1.
# Create 2x2 array and print its attributes.


import numpy as np

# Simple array creation.
a = np.array([[0, 1],[2, 3],[4, 5],[6, 7]])

# Print out the values of the array.
print(a)

print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension -', a.ndim)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Shape = (4, 2)
Size = 8
Dimension - 2


In [184]:
# Question 2.
# Create an array of dimension (1,10) and sort it in ascending and descending order.

a = np.array([[5, 1, 9, 3, 0, 4, 2, 7, 8, 6]])

# Print out the values of the array.
print(a)

print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension -', a.ndim)

#sort in ascending order
a_sorted_asc = np.sort(a)
a_sorted_asc








[[5 1 9 3 0 4 2 7 8 6]]
Shape = (1, 10)
Size = 10
Dimension - 2


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [185]:
#sort in descending order
a_sorted_des = -np.sort(-a)
a_sorted_des

array([[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [186]:
# Question 3.
# Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]].

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
X = np.reshape(x, (-1, 3))
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [188]:
# Question 4.
# Stack two arrays of any size horizontally and vertically.

# Vertical stacking of arrays.
A = np.array([[1, 2, 3, 6],
       [4, 5, 6, 9],
       [7, 8, 9, 4]])
A


array([[1, 2, 3, 6],
       [4, 5, 6, 9],
       [7, 8, 9, 4]])

In [189]:
B= np.array([[10, 20, 30,40],
       [40, 50, 60,70]])
B

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [190]:

np.vstack((A,B))

array([[ 1,  2,  3,  6],
       [ 4,  5,  6,  9],
       [ 7,  8,  9,  4],
       [10, 20, 30, 40],
       [40, 50, 60, 70]])

In [191]:
# Horizontal stacking of arrays.
C=np.array([[5, 7, 8, 9, 3],
    [8, 9, 2, 7, 2],
    [4, 5, 7, 7, 1]])
C

array([[5, 7, 8, 9, 3],
       [8, 9, 2, 7, 2],
       [4, 5, 7, 7, 1]])

In [192]:
D=np.array([[8, 6],
    [3, 5],
    [9, 2]])
D

array([[8, 6],
       [3, 5],
       [9, 2]])

In [193]:
np.hstack((C,D))

array([[5, 7, 8, 9, 3, 8, 6],
       [8, 9, 2, 7, 2, 3, 5],
       [4, 5, 7, 7, 1, 9, 2]])

In [0]:
# Question 5.
#Create two array of same size and find commom elements.

# Finding the common elements in two arrays

C=np.array([[5, 7, 15, 9, 3],
    [14, 9, 2, 7, 2],
    [4, 5, 7, 7, 1]])

In [195]:
print('size =', C.size)
print('shape =',C.shape)


size = 15
shape = (3, 5)


In [196]:
D=np.array([[1, 3, 11],
    [2, 8, 2],
    [13, 9, 1],
    [15, 6, 7],
    [16, 8, 7],])

print('size =', D.size)
print('shape =',D.shape)

# Note that C and D have the same size, but different shape.

size = 15
shape = (5, 3)


In [197]:
np.intersect1d(C, D)

array([ 1,  2,  3,  7,  9, 15])

In [198]:
# Question 6.
# Finding the minumum and maximum values in each row and column of an array.

X = np.array([[12, 2, 3, 5, 8],
              [11, 15, 3, 3, 15],
              [6, 8, 11, 19, 1],
              [4, 11, 2, 7, 5],
              [4, 16, 6, 16, 17]])

X



array([[12,  2,  3,  5,  8],
       [11, 15,  3,  3, 15],
       [ 6,  8, 11, 19,  1],
       [ 4, 11,  2,  7,  5],
       [ 4, 16,  6, 16, 17]])

In [199]:
(num_rows,num_cols)=X.shape
num_rows

5

In [200]:
num_cols

5

In [201]:
for i in range(num_rows):
  print('Row:', i, 'Minimum is' , min(X[i,:]), 'Maximum is',  max(X[i,:]))

Row: 0 Minimum is 2 Maximum is 12
Row: 1 Minimum is 3 Maximum is 15
Row: 2 Minimum is 1 Maximum is 19
Row: 3 Minimum is 2 Maximum is 11
Row: 4 Minimum is 4 Maximum is 17


In [202]:
for j in range(num_rows):
  print('Column:', j, 'Minimum is' , min(X[:,j]), 'Maximum is',  max(X[:,j]))

Column: 0 Minimum is 4 Maximum is 12
Column: 1 Minimum is 2 Maximum is 16
Column: 2 Minimum is 2 Maximum is 11
Column: 3 Minimum is 3 Maximum is 19
Column: 4 Minimum is 1 Maximum is 17


In [203]:
# Question 7.
# Create an array of size 100 and compute the mean, median, standard deviation.

X=np.random.random((5, 20))
X



array([[0.05649499, 0.83423617, 0.8046018 , 0.93859758, 0.3542794 ,
        0.24056857, 0.21789578, 0.34393091, 0.27303193, 0.00587143,
        0.48179019, 0.34755425, 0.12861787, 0.29305527, 0.90919621,
        0.00797437, 0.72200813, 0.58500182, 0.17285868, 0.09107312],
       [0.15398085, 0.33306051, 0.5260643 , 0.9791114 , 0.15127592,
        0.88121332, 0.67314549, 0.14006843, 0.91312961, 0.31519437,
        0.5338472 , 0.57237264, 0.81723192, 0.06095924, 0.29563244,
        0.20005566, 0.27729281, 0.21562185, 0.32173179, 0.94864552],
       [0.13833101, 0.20312749, 0.77840692, 0.92942846, 0.39681191,
        0.81245036, 0.89774153, 0.9414164 , 0.55069463, 0.79378146,
        0.79024456, 0.5809957 , 0.87562958, 0.11172521, 0.37876424,
        0.04366037, 0.40141518, 0.88181569, 0.8494062 , 0.49246538],
       [0.71712964, 0.2791918 , 0.06526429, 0.25000038, 0.33434721,
        0.89916618, 0.43831775, 0.20304626, 0.66702961, 0.01753925,
        0.52571611, 0.85016499, 0.50707362, 0

In [204]:
X.size

100

In [205]:
np.mean(X)

0.47834731615808274

In [206]:
np.median(X)

0.42313286285860036

In [207]:
np.std(X)

0.29598440856723945