<a href="https://colab.research.google.com/github/DavidB363/file-store/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# My Recommender System

import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [63]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv',header=None)


df_dropped=df.drop(df.columns[0],1)
print(df_dropped)
df=df_dropped

         1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]


In [0]:
# print(df.iloc[0,0])

In [65]:
print(df)

         1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]


In [0]:
# print(df_dropped.iloc[0,0])

In [0]:
# arr = df.values
# print(arr.shape)
#print(arr_full)
# print(df.iloc[0,0])

In [68]:
rated = np.where(arr!=99)
print(rated[0].shape)
print(rated[0])
print(rated[1])
print(len(rated[0]), rated[1].shape)

(1810455,)
[    0     0     0 ... 24982 24982 24982]
[ 0  1  2 ... 69 70 86]
1810455 (1810455,)


In [0]:

def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  print('idx',idx)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [70]:
new_arr, idx = replace(arr, 0.1)
print(idx)

idx [ 336213 1006850  570795 ... 1049645  276805 1548846]
(array([ 4683, 13960,  7911, ..., 14548,  3876, 21374]), array([30, 74, 29, ..., 20, 51, 53]))


In [0]:
# arr[idx[0][0], idx[1][0]]

In [0]:
# new_arr[idx[0][0], idx[1][0]]

In [0]:
# Set the number of latent factors to 2.

n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
# latent_item_features

In [0]:
# latent_user_preferences

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.001):
#def train(user_id, item_id, rating, alpha=0.01):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    



#def sgd(iterations=300000):
def sgd(iterations=10):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = [] 
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        # if (iteration % 10000) == 0:
        if (iteration % 1) == 0:
            print(mse)

In [77]:
sgd(10)  # Note how the MSE decreases with the number of iterations


24.50910986028026
22.311684193665222
20.131764082858144
18.22061371780292
17.727968909213168
17.676780390780937
17.71365435686474
17.787678740068774
17.894652933939852
18.04970209045758


In [0]:
predictions = np.zeros(shape=(latent_user_preferences.shape[0], latent_item_features.shape[0]))
#print(user_features_weights)
#print(item_features_weights)
for user_id in range(latent_user_preferences.shape[0]):
    for item_id in range(latent_item_features.shape[0]):
        predictions[user_id, item_id] =  predict_rating(user_id, item_id)

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [80]:
comparison_data

1    ...                          100
0      (-7.82, -2.8222363471700067)  ...  (99.0, -1.2460947526565862)
1          (4.08, 2.29152897660323)  ...   (1.07, 2.0524081133212984)
2         (99.0, 6.679351862430813)  ...    (99.0, 8.068748882698012)
3        (99.0, 1.3263230122935477)  ...    (99.0, 2.609240586332998)
4          (8.5, 3.185938288969421)  ...   (99.0, 4.6365633801600525)
...                             ...  ...                          ...
24978     (0.44, 3.531164122650708)  ...    (7.43, 5.168644013334407)
24979    (9.13, 1.0788308876594062)  ...   (8.45, 0.7771108916505926)
24980   (99.0, -0.6965929312904137)  ...  (99.0, -0.5262685332700954)
24981   (99.0, -1.8644278190692505)  ...  (99.0, -1.0597447302194558)
24982    (2.43, 3.7376232378900838)  ...     (99.0, 4.94423783351142)

[24983 rows x 100 columns]