<a href="https://colab.research.google.com/github/DavidB363/file-store/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# My Recommender System

import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [41]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv')
df=df.drop(df.columns[0],1)
print(df)

       -7.82   8.79  -9.66  -8.16  -7.52  ...  99.22  -5.63  99.23  99.24  99.25
0       4.08  -0.29   6.36   4.37  -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
1      99.00  99.00  99.00  99.00   9.03  ...  99.00  99.00  99.00  99.00  99.00
2      99.00   8.35  99.00  99.00   1.80  ...  99.00  99.00  99.00  99.00  99.00
3       8.50   4.61  -4.17  -5.39   1.36  ...   1.55   3.11   6.55   1.80   1.60
4      -6.17  -3.54   0.44  -8.50  -7.09  ...  -3.35   0.05  -9.08  -5.05  -3.45
...      ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24977   0.44   7.43   9.08   2.33   3.20  ...   9.03   6.55   8.69   8.79   7.43
24978   9.13  -8.16   8.59   9.08   0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24979  99.00  99.00  99.00  99.00  -7.77  ...  99.00  99.00  99.00  99.00  99.00
24980  99.00  99.00  99.00  99.00  -9.71  ...  99.00  99.00  99.00  99.00  99.00
24981   2.43   2.67  -3.98   4.27  -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24982 rows x 100 columns]


In [42]:
arr = df.values
print(arr.shape)
#print(arr_full)

(24982, 100)


In [43]:
rated = np.where(arr!=99)
print(rated[0].shape)
print(rated[0])
print(rated[1])
print(len(rated[0]), rated[1].shape)

(1810381,)
[    0     0     0 ... 24981 24981 24981]
[ 0  1  2 ... 69 70 86]
1810381 (1810381,)


In [0]:

def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  print('idx',idx)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [45]:
new_arr, idx = replace(arr, 0.1)
print(idx)

idx [1769524 1509023 1777710 ... 1389921 1535663  454779]
(array([24422, 20816, 24538, ..., 19184, 21181,  6308]), array([ 4, 14, 23, ..., 49,  5,  0]))


In [0]:
# arr[idx[0][0], idx[1][0]]

In [0]:
# new_arr[idx[0][0], idx[1][0]]

In [0]:
# Set the number of latent factors to 2.

n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
# latent_item_features

In [0]:
# latent_user_preferences

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
#def train(user_id, item_id, rating, alpha=0.01):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    



#def sgd(iterations=300000):
def sgd(iterations=10):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = [] 
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        # if (iteration % 10000) == 0:
        if (iteration % 1) == 0:
            print(mse)

In [52]:
sgd(10)  # Note how the MSE decreases with the number of iterations


26.200693919286657
25.271343905914478
24.983574695050837
24.764657831085323
24.552591386759648
24.33895371949194
24.122981218739138
23.905515368972633
23.687854743603605
23.471439333509874


In [0]:
predictions = np.zeros(shape=(latent_user_preferences.shape[0], latent_item_features.shape[0]))
#print(user_features_weights)
#print(item_features_weights)
for user_id in range(latent_user_preferences.shape[0]):
    for item_id in range(latent_item_features.shape[0]):
        predictions[user_id, item_id] =  predict_rating(user_id, item_id)

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [57]:
comparison_data

-7.82  ...                        99.25
0        (4.08, 0.9448574539576066)  ...    (1.07, 1.477115637422665)
1         (99.0, 1.666997727711148)  ...   (99.0, 2.6114017105906964)
2         (99.0, 1.679886595801374)  ...    (99.0, 2.602002590215961)
3         (8.5, 1.6698925172905565)  ...    (1.6, 2.5556451713948363)
4      (-6.17, 0.42269258176973284)  ...  (-3.45, 0.6235675664938902)
...                             ...  ...                          ...
24977    (0.44, 2.0428472942268634)  ...   (7.43, 3.1559045006369937)
24978    (9.13, 0.9004455133423303)  ...   (8.45, 1.3618337482912883)
24979    (99.0, 0.7048758692380472)  ...   (99.0, 1.1033688539204918)
24980    (99.0, 0.9336815774218601)  ...   (99.0, 1.4227433729111993)
24981     (2.43, 1.966488984834478)  ...   (99.0, 3.0460167252641135)

[24982 rows x 100 columns]