<a href="https://colab.research.google.com/github/DavidB363/file-store/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# My Recommender System

import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv')
print(df)

        74  -7.82   8.79  -9.66  -8.16  ...  99.22  -5.63  99.23  99.24  99.25
0      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
1       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
2       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
4      100  -6.17  -3.54   0.44  -8.50  ...  -3.35   0.05  -9.08  -5.05  -3.45
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24977  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24978   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24979   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24980   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24982 rows x 101 columns]


In [37]:
arr_full = df.values
print(arr_full.shape)
print(arr_full)

(24982, 101)
[[100.     4.08  -0.29 ...   0.34  -4.32   1.07]
 [ 49.    99.    99.   ...  99.    99.    99.  ]
 [ 48.    99.     8.35 ...  99.    99.    99.  ]
 ...
 [ 39.    99.    99.   ...  99.    99.    99.  ]
 [ 37.    99.    99.   ...  99.    99.    99.  ]
 [ 72.     2.43   2.67 ...  99.    99.    99.  ]]


In [38]:
# delete the first column of data
arr=arr_full[:,1:]
print(arr)

[[ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.    8.35 99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]


In [39]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810381 (1810381,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [41]:
new_arr, idx = replace(arr, 0.1)
print(idx)

(array([11078,   187, 18781, ..., 10591, 13536,  2394]), array([60, 40, 70, ..., 16, 96, 15]))


In [42]:
arr[idx[0][0], idx[1][0]]

4.95

In [43]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [45]:
latent_item_features

array([[0.253, 0.896],
       [0.114, 0.289],
       [0.286, 0.69 ],
       [0.558, 0.103],
       [0.467, 0.416],
       [0.787, 0.509],
       [0.835, 0.863],
       [0.791, 0.398],
       [0.56 , 0.227],
       [0.211, 0.937],
       [0.965, 0.674],
       [0.265, 0.624],
       [0.782, 0.121],
       [0.316, 0.354],
       [0.07 , 0.102],
       [0.607, 0.886],
       [0.041, 0.022],
       [0.658, 0.689],
       [0.727, 0.985],
       [0.133, 0.812],
       [0.503, 0.868],
       [0.417, 0.782],
       [0.885, 0.526],
       [0.212, 0.664],
       [0.724, 0.149],
       [0.837, 0.695],
       [0.242, 0.977],
       [0.446, 0.483],
       [0.961, 0.645],
       [0.884, 0.269],
       [0.251, 0.687],
       [0.607, 0.856],
       [0.697, 0.223],
       [0.775, 0.606],
       [0.255, 0.514],
       [0.87 , 0.501],
       [0.049, 0.195],
       [0.339, 0.845],
       [0.084, 0.491],
       [0.695, 0.309],
       [0.642, 0.471],
       [0.002, 0.086],
       [0.474, 0.114],
       [0.4

In [46]:
latent_user_preferences

array([[0.65 , 0.746],
       [0.359, 0.112],
       [0.684, 0.349],
       ...,
       [0.754, 0.623],
       [0.918, 0.751],
       [0.352, 0.151]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


#def train(user_id, item_id, rating, alpha=0.0001):
def train(user_id, item_id, rating, alpha=0.01):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=300000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print(mse)

In [0]:
sgd()  # Note how the MSE decreases with the number of iterations

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:18: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in subtract
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:34: RuntimeWarning: overflow encountered in square


nan
