<a href="https://colab.research.google.com/github/DavidB363/file-store/blob/master/Lab/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [233]:
# Question 1.
# Create 2x2 array and print its attributes.


import numpy as np

# Simple array creation.
a = np.array([[0, 1],[2, 3],[4, 5],[6, 7]])

# Print out the values of the array.
print(a)

print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension -', a.ndim)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Shape = (4, 2)
Size = 8
Dimension - 2


In [234]:
# Question 2.
# Create an array of dimension (1,10) and sort it in ascending and descending order.

a = np.array([[5, 1, 9, 3, 0, 4, 2, 7, 8, 6]])

# Print out the values of the array.
print(a)

print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension -', a.ndim)

#sort in ascending order
a_sorted_asc = np.sort(a)
a_sorted_asc








[[5 1 9 3 0 4 2 7 8 6]]
Shape = (1, 10)
Size = 10
Dimension - 2


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [235]:
#sort in descending order
a_sorted_des = -np.sort(-a)
a_sorted_des

array([[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [236]:
# Question 3.
# Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]].

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
X = np.reshape(x, (-1, 3))
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [238]:
# Question 4.
# Stack two arrays of any size horizontally and vertically.

# Vertical stacking of arrays.
A = np.array([[1, 2, 3, 6],
       [4, 5, 6, 9],
       [7, 8, 9, 4]])
A


array([[1, 2, 3, 6],
       [4, 5, 6, 9],
       [7, 8, 9, 4]])

In [239]:
B= np.array([[10, 20, 30,40],
       [40, 50, 60,70]])
B

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [240]:

np.vstack((A,B))

array([[ 1,  2,  3,  6],
       [ 4,  5,  6,  9],
       [ 7,  8,  9,  4],
       [10, 20, 30, 40],
       [40, 50, 60, 70]])

In [241]:
# Horizontal stacking of arrays.
C=np.array([[5, 7, 8, 9, 3],
    [8, 9, 2, 7, 2],
    [4, 5, 7, 7, 1]])
C

array([[5, 7, 8, 9, 3],
       [8, 9, 2, 7, 2],
       [4, 5, 7, 7, 1]])

In [242]:
D=np.array([[8, 6],
    [3, 5],
    [9, 2]])
D

array([[8, 6],
       [3, 5],
       [9, 2]])

In [243]:
np.hstack((C,D))

array([[5, 7, 8, 9, 3, 8, 6],
       [8, 9, 2, 7, 2, 3, 5],
       [4, 5, 7, 7, 1, 9, 2]])

In [0]:
# Question 5.
#Create two array of same size and find commom elements.

# Finding the common elements in two arrays

C=np.array([[5, 7, 15, 9, 3],
    [14, 9, 2, 7, 2],
    [4, 5, 7, 7, 1]])

In [245]:
print('size =', C.size)
print('shape =',C.shape)


size = 15
shape = (3, 5)


In [246]:
D=np.array([[1, 3, 11],
    [2, 8, 2],
    [13, 9, 1],
    [15, 6, 7],
    [16, 8, 7],])

print('size =', D.size)
print('shape =',D.shape)

# Note that C and D have the same size, but different shape.

size = 15
shape = (5, 3)


In [247]:
np.intersect1d(C, D)

array([ 1,  2,  3,  7,  9, 15])

In [248]:
# Question 6.
# Finding the minumum and maximum values in each row and column of an array.

X = np.array([[12, 2, 3, 5, 8],
              [11, 15, 3, 3, 15],
              [6, 8, 11, 19, 1],
              [4, 11, 2, 7, 5],
              [4, 16, 6, 16, 17]])

X



array([[12,  2,  3,  5,  8],
       [11, 15,  3,  3, 15],
       [ 6,  8, 11, 19,  1],
       [ 4, 11,  2,  7,  5],
       [ 4, 16,  6, 16, 17]])

In [249]:
(num_rows,num_cols)=X.shape
num_rows

5

In [250]:
num_cols

5

In [251]:
for i in range(num_rows):
  print('Row:', i, 'Minimum is' , min(X[i,:]), 'Maximum is',  max(X[i,:]))

Row: 0 Minimum is 2 Maximum is 12
Row: 1 Minimum is 3 Maximum is 15
Row: 2 Minimum is 1 Maximum is 19
Row: 3 Minimum is 2 Maximum is 11
Row: 4 Minimum is 4 Maximum is 17


In [252]:
for j in range(num_rows):
  print('Column:', j, 'Minimum is' , min(X[:,j]), 'Maximum is',  max(X[:,j]))

Column: 0 Minimum is 4 Maximum is 12
Column: 1 Minimum is 2 Maximum is 16
Column: 2 Minimum is 2 Maximum is 11
Column: 3 Minimum is 3 Maximum is 19
Column: 4 Minimum is 1 Maximum is 17


In [253]:
# Question 7.
# Create an array of size 100 and compute the mean, median, standard deviation.

X=np.random.random((5, 20))
X



array([[0.13215568, 0.97941947, 0.95771065, 0.32091393, 0.27850212,
        0.49301978, 0.36955509, 0.25262951, 0.75481577, 0.71688464,
        0.52136292, 0.30067931, 0.05952244, 0.05053446, 0.88985275,
        0.86684929, 0.23473161, 0.48059671, 0.77664147, 0.76731619],
       [0.20911564, 0.04876937, 0.71031946, 0.4626949 , 0.78025397,
        0.05400938, 0.14163959, 0.27552166, 0.01751964, 0.50012748,
        0.92958092, 0.28998319, 0.52949798, 0.15140642, 0.10692326,
        0.23209376, 0.6716714 , 0.99386848, 0.57710039, 0.32193847],
       [0.51811047, 0.03401574, 0.60265817, 0.13852065, 0.01437849,
        0.92992956, 0.20934455, 0.01529581, 0.34608702, 0.91041777,
        0.99347457, 0.77349687, 0.81587948, 0.61794478, 0.8950625 ,
        0.26466779, 0.21706759, 0.05585834, 0.81987209, 0.31364926],
       [0.0848635 , 0.67392747, 0.59228792, 0.7958714 , 0.55806838,
        0.54446877, 0.26985064, 0.83767313, 0.55049573, 0.77074962,
        0.61247117, 0.74628214, 0.52341358, 0

In [254]:
X.size

100

In [255]:
# Mean.
np.mean(X)

0.4721753822338026

In [256]:
# Median.
np.median(X)

0.48680824458762906

In [257]:
# Standard Deviation.
np.std(X)

0.3039582399478298

In [262]:
# Question 8.
# Normalize a 5x5 random matrix.

X=np.random.random((5, 5))
X= 2020*X
X



array([[1350.58082628,  686.73942804, 1127.17694601, 1872.24837093,
         524.05791516],
       [ 352.35717247, 1017.52950821,  285.81352039,  396.05773342,
        1062.04512036],
       [ 279.85619681,  160.77248986, 1448.62766351, 1797.07859172,
        1500.58610142],
       [1397.14017396, 1481.43656875, 1797.38526819, 1442.56858776,
         528.68933427],
       [ 389.70007188, 1984.02372228, 1953.58904572,  761.37783589,
         149.48217979]])

In [264]:
# This is ONE way to normalise the matrix.
# Subtract the mean.
X = X - X.mean()
# Divide by the maximum.
X = X / X.max()
# Numbers generated are between -1 and 1.
X

array([[ 0.33611597, -0.35962742,  0.10197605,  0.8828531 , -0.53012686],
       [-0.71007896, -0.01294068, -0.77982048, -0.6642783 ,  0.03371421],
       [-0.78606409, -0.91087056,  0.43887461,  0.80407091,  0.49332999],
       [ 0.3849128 ,  0.4732602 ,  0.80439233,  0.43252435, -0.52527287],
       [-0.67094149,  1.        ,  0.96810274, -0.28140214, -0.92270344]])

In [0]:
# Question 11.
#
# Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?
#
# The matrix equation y=Ax can be written using indices:-
# y(k)= Sum over j: A(k,j)*x(j)
#
# A generalisation to higher dimensions could be;
#
# y(k) = Sum over i and j: A(i,j,k)*x(i,j)
#
# In the example i and j would range from 1 to 4. (0 to 3 in Python!),
# and k would range from 1 to 3 (0 to 2).
# So A would be a 3 by 4 by 4 matrix,  x a 4 by 4 matrix , and y a 3 by 1 matrix.
#
